export const SET_APP_INFO_DATA = 'SET_APP_INFO_DATA';
export const SET_APP_INFO_PENDING = 'SET_APP_INFO_PENDING';
export const SET_APP_INFO_REJECTED = 'SET_APP_INFO_REJECTED';

export const SET_INPUT_URL = 'SET_INPUT_URL';
export const SET_INPUT_WORD = 'SET_INPUT_WORD';
export const CONFIRM_CHECK = 'CONFIRM_CHECK';