export const SET_APP_INFO_DATA = 'SET_APP_INFO_DATA';
export const SET_APP_INFO_PENDING = 'SET_APP_INFO_PENDING';
export const SET_APP_INFO_REJECTED = 'SET_APP_INFO_REJECTED';


///////////////////////// Part POST api/content/check
export const SET_INPUT_URL = 'SET_INPUT_URL';
export const SET_INPUT_WORD = 'SET_INPUT_WORD';
export const SET_POST_API_CONTENT_CHECK_PENDING = 'SET_POST_API_CONTENT_CHECK_PENDING';
export const SET_POST_API_CONTENT_CHECK_DATA = 'SET_POST_API_CONTENT_CHECK_DATA';
export const SET_POST_API_CONTENT_CHECK_REJECTED = 'SET_POST_API_CONTENT_CHECK_REJECTED';